### ISSUE TITLE
Server can't start with the new version

### ISSUE THREAD

**Issue by RedAlex** [lazerzes/Anvil-Enchantments#13]
My server don't start with the new version.
AnvilEnchantments-1.11.2-1.3.1

http://pastebin.com/tvJBZVK3

**Comment by sensdoggo** [comment]
I believe I have fixed the issue. I am running one last test before releasing it.

**Comment by sensdoggo** [comment]
There is a new live build. Please go grab version[ 1.3.1.1 of Anvil Enchantments](https://minecraft.curseforge.com/projects/anvil-enchantments/files/2393212).

If there are anymore problems please tell me.

**Comment by RedAlex** [comment]
Working.

**Comment by sensdoggo** [comment]
Great! Thanks for the followup. Enjoy the mod.
