### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by Zygus42** [lazerzes/Anvil-Enchantments#14]
anvils-1.10.2-1.2.2.0
forge-1.10.2-12.18.3.2254
jei_1.10.2-3.14.7.415
no other mods at all

Mod is showing as running, but no recipes in JEI, and book + iron ingot on anvil has no outcome showing, which by the example video it should.

Log:

[latest.log.txt](https://github.com/lazerzes/Anvil-Enchantments/files/849622/latest.log.txt)

**Comment by sensdoggo** [comment]
JEI Integration is only available in 1.11.2 


Please update to the newest version.
