### ISSUE TITLE
1.12 Update 

### ISSUE THREAD

**Issue by JavaNinjaB** [lazerzes/Anvil-Enchantments#17]
All in the title - ideas?

Thanks!

**Comment by sensdoggo** [comment]
Are you trying to use this mod in a 1.12.2 Minecraft instance? If so I haven't had time to update this mod yet. I am working on it, but I am a college atudent.

**Comment by JavaNinjaB** [comment]
Yes, I m trying 12.2 - the site I downloaded from indicated this was a 12.2 version.No worries and thanks for the response. This is a great mode and I don't need to re-generate my world in order bring it in, so I'll just wait impatiently...😎Regards,Kevin StringerIBM Cloud & CognitiveIBM Certified Solution Advisor - Cloud SolutionsPMI Certified Project Manager - PMPITIL V3 Certified - IT Service Managementmobile: 773.251.4045email: kevinstringer@us.ibm.com(sent from my mobile phone - please excuse the brevity and any odd spellings or word choices)



   Rei Armenia --- Re: [lazerzes/Anvil-Enchantments] Anvils 10.2-12.2 says it needs 10.2 and won't let 12.2 load.. (#17) --- 
    From:"Rei Armenia" <notifications@github.com>To:"lazerzes/Anvil-Enchantments" <Anvil-Enchantments@noreply.github.com>Cc:"JavaNinjaB" <kevinstringer@us.ibm.com>, "Author" <author@noreply.github.com>Date:Thu, Jan 4, 2018 11:19 PMSubject:Re: [lazerzes/Anvil-Enchantments] Anvils 10.2-12.2 says it needs 10.2 and won't let 12.2 load.. (#17)
  
  Are you trying to use this mod in a 1.12.2 Minecraft instance? If so I haven't had time to update this mod yet. I am working on it, but I am a college atudent.

**Comment by sensdoggo** [comment]
No problem, for future reference the only location that I have posted this mod to is CurseForge, which there is a link to in the readme of this project, i appreciate your patience. I will be updating this mod over the next week and will close this issue when the 1.12 update is finished!

**Comment by JavaNinjaB** [comment]
You da Man!

I'd say your studies come first, but mine didn't and I don't want to be a
hypocrite...

;-)

                                                                                      
                                                                                      
   Regards,                                                                           
                                                                                      
                                                                                      
   KEVIN STRINGER                                                                     
   Cloud & Cognitive Technical                                                        
   Lead (C&CTL)                                                                       
   IBM Cloud & Cognitive,                                                             
   Industrial Products                                                                
                                                                                      
   IBM Certified Solution Advisor                                                     
   - Cloud Solutions                                                                  
   PMI Certified Project Manager -                                                    
   PMP                                                                                
   ITIL v3 Certified - IT Service                                                     
   Management                                                                         
                                                                                      


                                                                                      
                                                                                      
                                                                                      
   Mobile: 1-773-251-4045                                                         IBM 
   E-mail: KevinStringer@US.IBM.com                                                   
   Zoom Room: https://zoom.us/j/5974644386                                            
                                                                                      
                                                                                      
                                                                                      


                                                                                      
                                                                                      
                                                                                      
                                                                                      
                                                                                      






From:	Rei Armenia <notifications@github.com>
To:	lazerzes/Anvil-Enchantments
            <Anvil-Enchantments@noreply.github.com>
Cc:	JavaNinjaB <kevinstringer@us.ibm.com>, Author
            <author@noreply.github.com>
Date:	01/05/2018 03:24 PM
Subject:	Re: [lazerzes/Anvil-Enchantments] Anvils 10.2-12.2 says it
            needs 10.2 and won't let 12.2 load.. (#17)



No problem, for future reference the only location that I have posted this
mod to is CurseForge, which there is a link to in the readme of this
project, i appreciate your patience. I will be updating this mod over the
next week and will close this issue when the 1.12 update is finished!


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sensdoggo** [comment]
Alright @JavaNinjaB 

I updated the mod to 1.12.2 you can find it on the curse forge website.

I shall link it here. [ANVIL ENCHANTMENTS](https://minecraft.curseforge.com/projects/anvil-enchantments)

**Comment by JavaNinjaB** [comment]
Awesome!

I'm chugging away with it now. I don't see Sweeping Edge in the list, but I
think I've seen all the others.

No biggie!

Thanks again!

Kevin
                                                                                      
                                                                                      
   Regards,                                                                           
                                                                                      
                                                                                      
   KEVIN STRINGER                                                                     
   Cloud & Cognitive Technical                                                        
   Lead (C&CTL)                                                                       
   IBM Cloud & Cognitive,                                                             
   Industrial Products                                                                
                                                                                      
   IBM Certified Solution Advisor                                                     
   - Cloud Solutions                                                                  
   PMI Certified Project Manager -                                                    
   PMP                                                                                
   ITIL v3 Certified - IT Service                                                     
   Management                                                                         
                                                                                      


                                                                                      
                                                                                      
                                                                                      
   Mobile: 1-773-251-4045                                                         IBM 
   E-mail: KevinStringer@US.IBM.com                                                   
   Zoom Room: https://zoom.us/j/5974644386                                            
                                                                                      
                                                                                      
                                                                                      


                                                                                      
                                                                                      
                                                                                      
                                                                                      
                                                                                      






From:	Rei Armenia <notifications@github.com>
To:	lazerzes/Anvil-Enchantments
            <Anvil-Enchantments@noreply.github.com>
Cc:	JavaNinjaB <kevinstringer@us.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	01/08/2018 04:03 PM
Subject:	Re: [lazerzes/Anvil-Enchantments] 1.12 Update (#17)



Alright @JavaNinjaB


I updated the mod to 1.12.2 you can find it on the curse forge website.


I shall link it here. ANVIL ENCHANTMENTS


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
