### ISSUE TITLE
Exception thrown during initialisation with v 2.0.1

### ISSUE THREAD

**Issue by GrumpyChunks** [lazerzes/Anvil-Enchantments#20]
This is in a single player world on Forge 2745, in a custom modpack, see log for full list of included mods and versions.

[Stacktrace/crash log](https://pastebin.com/SJ36VfJd).

Reverted back to 2.0.0 and the game starts up fine.

**Comment by sensdoggo** [comment]
...huh.


I'll look further into this later today. But I am not sure what's going on with that.

**Comment by sensdoggo** [comment]
Hello @BinaryCrafter .

this issue should be resolved 858b68e. Thank you for making me aware of it!


The file is currently awaiting approval, but once version 2.0.2 is available please tell me if it works for you.

**Comment by GrumpyChunks** [comment]
It's working perfectly for me now, thanks for fixiing this, and thanks for this great mod. It's one of those "must have" mods for vanilla style modded gameplay.
