### ISSUE TITLE
Recipe Changes Not Working + Fortune Enchant Broken

### ISSUE THREAD

**Issue by ChosenArchitect** [lazerzes/Anvil-Enchantments#21]
![2018-08-22_00 50 08](https://user-images.githubusercontent.com/35053440/44445162-9010b100-a5a5-11e8-873b-c681149e671e.png)

**Comment by sensdoggo** [comment]
Hello, can you please also post your edited recipe file.

**Comment by sensdoggo** [comment]
I am closing this issue as there is not enough information available.
 @ChosenArchitect 

If you believe this to be an error, please respond to this issue with:

- Any files that have been changed locally.


When this condition is met the issue may be reopened.

**Comment by ChosenArchitect** [comment]
With no files changed the Fortune I book just says err. I don't know if it is an error because of the item name required was dye (lapis). So I went to just change the name of the item required and the metadata and the changes don't seem to fix the problem and the items required doesn't change.

**Comment by ChosenArchitect** [comment]
File Unchanged - https://pastebin.com/njuFTTbz
File edited to change the required item - https://pastebin.com/B2BXTzqE
The changes don't seem to take.

Sorry for the late reply... I am really busy and sometimes don't catch all my emails.

**Comment by sensdoggo** [comment]
Don't worry about it. 

I'll re open the issue and take a look at it within the next couple of days.

**Comment by ChosenArchitect** [comment]
I think it may have been a conflict with quark... So changed the config to this and it now works. https://pastebin.com/yZSL6cHM

**Comment by sensdoggo** [comment]
Whoops sorry for disappearing on you. Started a new job recently.


Thanks for updating me on the issue.

Let me know if you have any issues.

**Comment by GrumpyChunks** [comment]
I've also had this issue, it would be nice if the default fortune recipe could be changed as per @ChosenArchitect's posted solution.

**Comment by sensdoggo** [comment]
@BinaryCrafter Thanks for the suggestion.

Im going to change the default recipe to use 2 lapis blocks, to be more in line with the original cost. 

I'll post here again when that is done.

**Comment by sensdoggo** [comment]
The default recipe has been changed.

I reworked the mod and tested it to ensure that it has better Mod Compatibility.

Feel free to let me know if any other problems occur.

Thanks for your patience, I will be closing this issue now.
