### ISSUE TITLE
[Mod Compatibility] JEI now supports anvil recipes, but recipes from this mod dont show up

### ISSUE THREAD

**Issue by Lothrazar** [lazerzes/Anvil-Enchantments#8]
https://github.com/mezz/JustEnoughItems/pull/732

Recipes are working but not visible in their interface.  used latest version  jei_1.11.2-4.2.8.244 

Will probably need to add a recipe wrapper and an optional.interface 

https://github.com/mezz/JustEnoughItems/wiki/Recipe-Wrappers

**Comment by sensdoggo** [comment]
It should be as simple as converting the Recipe into JEI's format. I'll look into it!

**Comment by sensdoggo** [comment]
I began work on this, currently running into an issue with actually getting them all to show, and potions are currently not fully working. But, its a start!

Changes can be found [here.](https://github.com/lazerzes/Anvil-Enchantments/tree/master/src/main/java/com/lazerzes/anvils/intergration/jei)

**Comment by sensdoggo** [comment]
Fully Done!
